### ISSUE TITLE
Correctly handle \n when writing file

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#127]
We should correctly handle '\n' when writing data into file. When a performance script has "\n" in it for example:

```python
print("Hello, Thoth\n")
```

The file placed into container image is:

```python
print("Hello, Thoth
")
```

Which causes syntax errors. We should correctly escape it (see dockerfile.py file).

**Comment by goern** [comment]
hmm, we should provide a container image name to amun to execute that, this container image should include the microbenchmark.

**Comment by saisankargochhayat** [comment]
https://paste.ofcode.org/PrLfLsKSwuUr4LamXQvFaN
This is what the `create_dockerfile` return's when I tried passing the sample from the stage amun link, if I delete the part above FROM, it seems to build as a docker image also, is that what we were expecting? I am not sure.

**Comment by fridex** [comment]
Check the input string - on the API endpoint, there is requested:

```json
  "script": "#!/usr/bin/bash\necho \"Here should be run tests...\"\n",
```

that is transformed to (based on your paste):

```dockerfile
RUN echo -e "#!/usr/bin/bash\n\\necho \"Here should be run tests...\"\n\\n" > "/home/amun/script"
```

I think the expected content of the file is (based on the API endpoint input):

```
#!/usr/bin/bash
echo "Here should be run tests..."
```

Will the `echo` invocation (as done in the generated Dockerfile) produce same file as desired?

**Comment by saisankargochhayat** [comment]
![image](https://user-images.githubusercontent.com/9396452/76559809-38cb7d80-6476-11ea-9822-98b9b4bcaf31.png)
I think they produce the same result

**Comment by fridex** [comment]
> do you want the extra space to be removed?

it would be great if they match

**Comment by saisankargochhayat** [comment]
This would be just for the value of the key `script` right?

**Comment by fridex** [comment]
I think it applies to all the `_write_file_string` invocations:

https://github.com/thoth-station/amun-api/blob/bcdfc3b8a3945283c2e12e0ff2d5e5bb975b2326/amun/dockerfile.py#L76

So also for writing the lock file, requirements file or pip configuration.

**Comment by goern** [comment]
whats the status of this?
