### ISSUE TITLE
Create roles for inspector service account

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#128]
**Is your feature request related to a problem? Please describe.**

As of now, we assign cluster admin to the inspection service account. It would be better to create a fine-granted access control for this service account.

**Describe the solution you'd like**

Have roles defined on deployment (from top of my head, some might be missing):

* create jobs (later CRDs) in inspection namespace
* create builds (later CRDs) in inspection namespace
* create configmap (later CRDs) in inspection namespace
* list templates in infra namespace

**Describe alternatives you've considered**

Stick with the current solution - having a edit cluster role.

**Additional context**

https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by goern** [comment]
@fridex this is done, isnt it?
