### ISSUE TITLE
What happens if a inspection job with CPU requirements gets evicted?

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#140]
Check if configuration option `requiredDuringSchedulingIgnoredDuringExecution` applies also during re-scheduling done if a pod gets evicted from the original node where this node selector was applied during scheduling.

https://github.com/thoth-station/amun-api/blob/348dd021c19ee5edff35f7a4e5fad9d968620f2a/openshift/inspectJobWithCPU-template.yaml#L82

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
yes

**Comment by bissenbay** [comment]
@goern @fridex I read the documentation on Kubernetes on [assigning pods to nodes ](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/) and couldn't find the info what happens once a pod is evicted and rescheduled. Like does the scheduler take into account the affinity terms we have assigned? So, then I posted a question on [stackoverflow](https://stackoverflow.com/questions/61216214/will-requiredduringschedulingignoredduringexecution-nodeaffinity-persist-if-a-po). Will update if get any response.
What do you think, can we check that like scheduling an inspection-job and intentionally kill it, so to let it to be recreated and see whether the node affinity terms are considered or not?

**Comment by fridex** [comment]
What about this part:

> Thus an example of `requiredDuringSchedulingIgnoredDuringExecution` would be “only run the pod on nodes with Intel CPUs” 

What confused me originally was the "`IngoredDuringExecution`" part, but it looks like it has a different purpose:

> In the future we plan to offer requiredDuringSchedulingRequiredDuringExecution which will be just like requiredDuringSchedulingIgnoredDuringExecution except that it will evict pods from nodes that cease to satisfy the pods’ node affinity requirements.

That is, when node labels change during the pod run (unlikely in our case).

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity

**Comment by bissenbay** [comment]
> What about this part:
> 
> > Thus an example of `requiredDuringSchedulingIgnoredDuringExecution` would be “only run the pod on nodes with Intel CPUs”
> > > @fridex Do you think we can imply that this option would guarantee us to pick nodes according our conditions when they are recreated? Should we close this issue?
> 
> What confused me originally was the "`IngoredDuringExecution`" part, but it looks like it has a different purpose:
> 
> > In the future we plan to offer requiredDuringSchedulingRequiredDuringExecution which will be just like requiredDuringSchedulingIgnoredDuringExecution except that it will evict pods from nodes that cease to satisfy the pods’ node affinity requirements.
> 
> That is, when node labels change during the pod run (unlikely in our case).
> 
> https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity

**Comment by fridex** [comment]
> Should we close this issue?

I think we can safely close it - I leave the final decision up to you.
