### ISSUE TITLE
Add option to specify resource and hardware requirements

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#34]
As an Amun user, I would like to have an ability to set requirements for the runtime and build time environment via JSON exposed on the `/inspect` endpoint. For this purpose we should introduce separate configuration options in the JSON supplied on endpoint:

```
{
  "base": "fedora:28",
  "build": {
    "requests": {
     "cpu": {...},
     "memory": {...}
    }
  },
  "run": {
    "requests": {
     "cpu": {...},
     "memory": {...}
    }
  }
}

**Comment by fridex** [comment]
Related: #6 #33

**Comment by fridex** [comment]
work that needs to be done:

- [ ] adjust the swagger definition so that the input JSON accepts memory requests
- [ ] adjust OpenShift template so that CPU/memory requirements are passed as parameters (set some reasonable default value)
- [ ] pass memory/CPU requirements to template from API server

**Comment by goern** [comment]
Trello Card: https://trello.com/c/CSysvOus

**Comment by ace2107** [comment]
Closed with https://github.com/thoth-station/amun-api/pull/46
