### ISSUE TITLE
adjust the Argo workflow

### ISSUE THREAD

**Issue by goern** [thoth-station/amun-api#418]
Adjust the workflow in a way it stores build logs on Ceph, similarly as results of inspection results are stored

**Comment by fridex** [comment]
Part of https://trello.com/c/IcKsEibX/

**Comment by pacospace** [comment]
Interesting future feature: https://github.com/argoproj/argo/issues/934

**Comment by fridex** [comment]
This is alrady implemented in the recent migration to Argo workflows.
