### ISSUE TITLE
Uniquely identifies every layer for automated results analysis using notebook and workflows

### ISSUE THREAD

**Issue by pacospace** [thoth-station/amun-api#553]
**Is your feature request related to a problem? Please describe.**
As Performance Engineer, Data Scientist, I want to visualize/make visualization about performance differences across all layers in the app, from the stack to the hardware, and see differences in performances. Currently from inspection data, we can distinguish the software stack layer, RPM installed as well, the image selected, CPU requested, the hardware used. All this information can be retrieved and used to differentiate the layers and identify unique features to differentiate visualization.

There is one thing not currently possible to identify from Amun results, which is the presence of optimized libraries (e.g. MKL) already present in the base image and not installed during a build. (You can see the base is different, but not the packages that are contained in the image)
This makes it more difficult to automate a notebook for analysis and visualization of results on all layers. Moreover relying on identifiers of an inspection might be also not possible always and not that safe to do.

**Describe the solution you'd like**
I would like to include a package-extract run in an inspection workflow task so that a new file is stored in the inspection that can be retrieved from a notebook to automatically find the information in the missing layer. In this way, we can find out the list of optimized libraries present in the image and differentiate that layer as well not just from the OS image name, version and base.

Reference: https://github.com/thoth-station/package-extract#example-of-extracting-installed-packages-inside-an-image

**Describe alternatives you've considered**

**Additional context**
Beside having an optimized library installed, we should have a way to know if it is set correctly to be used.

**Comment by fridex** [comment]
+1, except this should not go to amun. Amun is just "execution engine" for executing/verifying stacks. The component which triggers amun inspections should be responsible for scheduling container image analyses (if such thing is required).
 

> Beside having an optimized library installed, we should have a way to know if it is set correctly to be used.

I think this will require some human invervention - we will not check for correct library configuration. Wrong config of libs should be seen in the inspection results (as we have already seen for the mkl one).

**Comment by pacospace** [comment]
> +1, except this should not go to amun. Amun is just "execution engine" for executing/verifying stacks. The component which triggers amun inspections should be responsible for scheduling container image analyses (if such thing is required).
> 

So it should be an optional task for Dependency Monkey? Because if they are not linked, when we retrieve data in the notebook, we need to do many search in two different buckets to match the image analysis for a certain base image used in inspections, 


> > Beside having an optimized library installed, we should have a way to know if it is set correctly to be used.
> 
> I think this will require some human invervention - we will not check for correct library configuration. Wrong config of libs should be seen in the inspection results (as we have already seen for the mkl one).

Sounds good, the alternative is to add to the identifier+image+base at the moment to uniquely differentiate two inspection ids where all layers are the same except for libraries in the image

**Comment by fridex** [comment]
> > +1, except this should not go to amun. Amun is just "execution engine" for executing/verifying stacks. The component which triggers amun inspections should be responsible for scheduling container image analyses (if such thing is required).
> 
> So it should be an optional task for Dependency Monkey? Because if they are not linked, when we retrieve data in the notebook, we need to do many search in two different buckets to match the image analysis for a certain base image used in inspections,

+1, so adding a step to the dependency monkey workflow would do the trick. The final report of dependency monkey workflow would be (as of now): inspections scheduled + container image analyses id (which can be linked in the knowledge database).

We already produce "dependency monkey report" which states all the inspections scheduled (placed on ceph). We can add a report with container image analysis id as well.

> > > Beside having an optimized library installed, we should have a way to know if it is set correctly to be used.
> > 
> > 
> > I think this will require some human invervention - we will not check for correct library configuration. Wrong config of libs should be seen in the inspection results (as we have already seen for the mkl one).
> 
> Sounds good, the alternative is to use to the `image_base` name at the moment to uniquely differentiate two inspection not considering identifier where all layers are the same except for libraries in the image.

These are two different inspections to me.

**Comment by pacospace** [comment]
> > > +1, except this should not go to amun. Amun is just "execution engine" for executing/verifying stacks. The component which triggers amun inspections should be responsible for scheduling container image analyses (if such thing is required).
> > 
> > 
> > So it should be an optional task for Dependency Monkey? Because if they are not linked, when we retrieve data in the notebook, we need to do many search in two different buckets to match the image analysis for a certain base image used in inspections,
> 
> +1, so adding a step to the dependency monkey workflow would do the trick. The final report of dependency monkey workflow would be (as of now): inspections scheduled + container image analyses id (which can be linked in the knowledge database).
> 
> We already produce "dependency monkey report" which states all the inspections scheduled (placed on ceph). We can add a report with container image analysis id as well.
> 

+1 Sounds good to me.
> > > > Beside having an optimized library installed, we should have a way to know if it is set correctly to be used.
> > > 
> > > 
> > > I think this will require some human invervention - we will not check for correct library configuration. Wrong config of libs should be seen in the inspection results (as we have already seen for the mkl one).
> > 
> > 
> > Sounds good, the alternative is to use to the `image_base` name at the moment to uniquely differentiate two inspection not considering identifier where all layers are the same except for libraries in the image.
> 
> These are two different inspections to me.

Agree I will rely on image_base for now.
