### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#576]
**Is your feature request related to a problem? Please describe.**

As Amun user, I would like to trigger inspections that should run on GPU.

**Describe the solution you'd like**

Extend (or add) workflow templates so that they enable running inspections on GPU considering CUDA.

**Comment by goern** [comment]
as we have no GPU hardware available on op1st, I will downgrade the priority
/remove-priority important-soon
/priority important-longterm
