### ISSUE TITLE
Add hardware requirements for builds and inspection

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#6]
I, as an Amun user, would like to request specific hardware for builds and the actual inspection runs (CUDA on a node, specific CPU model, ...).

This should be provided as an input on API, the input should respect configuration (mount this configuration (JSON mapping HW to node selectors?) into a container from configmap).

If user does not specify hardware requirements, build/inspection pods are placed on any available node in the cluster.

**Comment by goern** [comment]
@sub-mod

**Comment by goern** [comment]
Trello Card: https://trello.com/c/CSysvOus

**Comment by fridex** [comment]
The PR was merged into the master, thus closing this issue.
