### ISSUE TITLE
Amun API failing all inspections

### ISSUE THREAD

**Issue by TomasJani** [thoth-station/amun-api#611]
**Describe the bug**
I tried using Amun API on MOC after two weeks and inspection that were previously working are now causing errors and since then I was not able to run one successful inspection.

**To Reproduce**
I used Amun API swagger.
1. Run [this](https://github.com/TomasJani/thoth-issue-predictor/blob/main/thoth_issue_predictor/loader/specifications/inspection-tf-dm-np-b1f362e5/specification) inspection on api/v1/inspect endpoint.

The id of this inspection when I ran it was `inspection-tf-dm-np-652c4c9b` and the result was [this](https://github.com/TomasJani/thoth-issue-predictor/blob/main/thoth_issue_predictor/loader/specifications/inspection-tf-dm-np-b1f362e5/response_1614699911595.json).

**Expected behavior**
In this case inspection should return 0 and the result should be stored and retrievable.

**Additional context**
Every other operation that I test around gathering finished inspections was working.

**Comment by harshad16** [comment]
Thanks for opening the issue. 
Checking on this

**Comment by harshad16** [comment]
This seems to be issue on the cluster side. we are working with our cluster team , to check on this.
This would take some more time to fix.

**Comment by TomasJani** [comment]
Thank's for letting me know. No problem, not blocking me yet.

**Comment by fridex** [comment]
Is this still relevant? I've tried to run an example scenario (`inspection-test-47b04a99`) and it looks like the amun service is operational again.

**Comment by TomasJani** [comment]
I tried it today and it seem to be a different kind of error. Now I'm not even able to get any response from the status endpoint. Always getting:
**500 Error: INTERNAL SERVER ERROR**
```json
{
  "details": {
    "datetime": "2021-03-15T19:45:06.803609",
    "type": "InternalServerError"
  },
  "error": "Internal server error occurred, please contact administrator with provided details."
}
```

**Comment by fridex** [comment]
Was able to reproduce it, looks like we get these internal errors.

@harshad16 Any logs that could be helpful to trace the issue here, please?

**Comment by fridex** [comment]
> Was able to reproduce it, looks like we get these internal errors.
> 
> @harshad16 Any logs that could be helpful to trace the issue here, please?

https://github.com/thoth-station/amun-api/issues/613 might be related? Issues with Ceph connection?

**Comment by harshad16** [comment]
This seems to be working well now.
```
STEP                             TEMPLATE                        PODNAME                                  DURATION  MESSAGE
 ✔ inspection-tf-dm-np-82da2caa  main                                                                                 
 ├-✔ inspection-build            inspection-build-template/main                                                       
 | ├---✔ prepare-env             prepare-env                     inspection-tf-dm-np-82da2caa-2303147930  11s         
 | ├---✔ imagestream             create-imagestream              inspection-tf-dm-np-82da2caa-3173139951  3s          
 | ├---✔ buildconfig             create-buildconfig              inspection-tf-dm-np-82da2caa-1993054743  3s          
 | ├---✔ build                   await-build                     inspection-tf-dm-np-82da2caa-2125250048  10m         
 | └---✔ buildlog-aggregation    aggregate-buildlog              inspection-tf-dm-np-82da2caa-3517325848  10s         
 └-✔ inspection-run              inspection-run-template/main                                                         
   ├---✔ job(0:0)                create-job                      inspection-tf-dm-np-82da2caa-2169131440  3m          
   └---✔ joblog-aggregation      aggregate-joblog                inspection-tf-dm-np-82da2caa-3371609287  14s  
``` 

The issue was with the storage, we have fixed the storage issue.
Please try it out and lets us know.

**Comment by TomasJani** [comment]
Thank you very much, Amun seems to work. Could the fixing in any way change Management API? I am not sure yet but it seems there is something wrong. I can't be sure because there are suddenly no logs.

**Comment by fridex** [comment]
> Could the fixing in any way change Management API? I am not sure yet but it seems there is something wrong. I can't be sure because there are suddenly no logs.

Could you provide steps to reproduce the issue you are observing? It will help us to check what is wrong.

**Comment by TomasJani** [comment]
For example default configuration or [this](https://github.com/TomasJani/thoth-issue-predictor/blob/catboost/thoth_issue_predictor/loader/dm_specifications/test_specs_6.json) or [this](https://github.com/TomasJani/thoth-issue-predictor/blob/catboost/thoth_issue_predictor/loader/dm_specifications/test_specs_7.json) specs.
Status message looks like this: 
```json
{
  "parameters": {
    "analysis_id": "dependency-monkey-210318115656-457a0c12f33d52dc"
  },
  "status": {
    "finished_at": "2021-03-18T11:57:32Z",
    "reason": null,
    "started_at": "2021-03-18T11:56:56Z",
    "state": "error"
  }
}
```

and logs return null.

**Comment by harshad16** [comment]
we have increased the time-to-live of the logs to 1hr , after that the logs wont be available for both inspection and dm:
```
STEP                                                TEMPLATE               PODNAME                                                     DURATION  MESSAGE
 ✔ dependency-monkey-210318190057-7574684031ea397e  dependency-monkey                                                                              
 ├-✔ dm                                             dm/dm                  dependency-monkey-210318190057-7574684031ea397e-958524179   2m          
 └-✔ graph-sync-dm(0)                               graph-sync/graph-sync  dependency-monkey-210318190057-7574684031ea397e-1006658923  19s  
 ```

I checked on the dependency monkey , we have updated the ceph to fix the dependency-moneky issues. It seems to be working now. 
 ```
 {
  "parameters": {
    "analysis_id": "dependency-monkey-210318190057-7574684031ea397e"
  },
  "status": {
    "finished_at": "2021-03-18T19:03:32Z",
    "reason": null,
    "started_at": "2021-03-18T19:00:58Z",
    "state": "succeeded"
  }
}
 ```
 
 Please try it out and let me know.

**Comment by TomasJani** [comment]
Thank you very much. I tested it and it worked.

**Comment by fridex** [comment]
Great! Thanks for the report and all the work done.

/close
