### ISSUE TITLE
Automatically gather relevant information about available hardware

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#7]
I, as Amun user, would like to have access to hardware information where the given pod was run. This should be leveraged by Amun in a structured and standardized format.

We can run an initcontainer that simply gathers this information before the inspection pod is run and places it into a JSON file on specified path - e.g. /home/amun/hw_info.json). This file should be always available and a user script given on API can automatically gather this file just by reading it.

**Comment by goern** [comment]
This is used to gather information about the environment Pods ran on, not to schedule pods.

**Comment by fridex** [comment]
Done in [amun-hwinfo](https://github.com/fridex/amun-hwinfo).
